"""add name and pics to assets

Revision ID: 0255751c95d5
Revises: 
Create Date: 2025-08-28 12:31:30.973865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0255751c95d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('pic', sa.String(length=200), nullable=True))
    op.add_column('assets', sa.Column('other_pics', sa.JSON(), nullable=True))
    op.add_column('assets', sa.Column('name', sa.String(length=100), nullable=True))
    op.execute("UPDATE assets SET name = 'Unknown' WHERE name IS NULL")
    op.alter_column("assets", "name", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'name')
    op.drop_column('assets', 'other_pics')
    op.drop_column('assets', 'pic')
    # ### end Alembic commands ###
