"""add sec tables n fields

Revision ID: 15bf5ca82f0f
Revises: 59e19fa8f118
Create Date: 2025-10-08 10:54:17.127628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bf5ca82f0f'
down_revision: Union[str, Sequence[str], None] = '59e19fa8f118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_fingerprints',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('ip_at_registration', sa.String(length=45), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_fingerprints_fingerprint_hash'), 'device_fingerprints', ['fingerprint_hash'], unique=False)
    op.create_index(op.f('ix_device_fingerprints_id'), 'device_fingerprints', ['id'], unique=False)
    op.create_table('ip_whitelist',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('whitelist_type', sa.String(length=20), nullable=False),
    sa.Column('whitelisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_whitelist_id'), 'ip_whitelist', ['id'], unique=False)
    op.create_index(op.f('ix_ip_whitelist_ip_address'), 'ip_whitelist', ['ip_address'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('ip_details', sa.JSON(), nullable=True),
    sa.Column('fraud_score', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_index(op.f('ix_login_attempts_id'), 'login_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_login_attempts_timestamp'), 'login_attempts', ['timestamp'], unique=False)
    op.create_table('mfa_codes',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('temp_session_token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfa_codes_id'), 'mfa_codes', ['id'], unique=False)
    op.create_index(op.f('ix_mfa_codes_temp_session_token'), 'mfa_codes', ['temp_session_token'], unique=True)
    op.create_table('temp_disable_logs',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('disabled_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_disable_logs_id'), 'temp_disable_logs', ['id'], unique=False)
    # op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('temp_disabled_until', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'login_attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('users', 'temp_disabled_until')
    op.drop_column('users', 'timezone')
    op.drop_index(op.f('ix_temp_disable_logs_id'), table_name='temp_disable_logs')
    op.drop_table('temp_disable_logs')
    op.drop_index(op.f('ix_mfa_codes_temp_session_token'), table_name='mfa_codes')
    op.drop_index(op.f('ix_mfa_codes_id'), table_name='mfa_codes')
    op.drop_table('mfa_codes')
    op.drop_index(op.f('ix_login_attempts_timestamp'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_ip_whitelist_ip_address'), table_name='ip_whitelist')
    op.drop_index(op.f('ix_ip_whitelist_id'), table_name='ip_whitelist')
    op.drop_table('ip_whitelist')
    op.drop_index(op.f('ix_device_fingerprints_id'), table_name='device_fingerprints')
    op.drop_index(op.f('ix_device_fingerprints_fingerprint_hash'), table_name='device_fingerprints')
    op.drop_table('device_fingerprints')
    # ### end Alembic commands ###
