"""convert some ids from int to str

Revision ID: 1eb44413307a
Revises: 8b0aa51b8226
Create Date: 2025-09-07 09:58:21.177705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eb44413307a'
down_revision: Union[str, Sequence[str], None] = '8b0aa51b8226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_disposals', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('asset_lifecycle_events', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('asset_revaluations', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('asset_transfers', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('assets', 'other_pics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('maintenance_requests', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=60),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance_requests', 'id',
               existing_type=sa.String(length=60),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('assets', 'other_pics',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('asset_transfers', 'id',
               existing_type=sa.String(length=60),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('asset_revaluations', 'id',
               existing_type=sa.String(length=60),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('asset_lifecycle_events', 'id',
               existing_type=sa.String(length=60),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('asset_disposals', 'id',
               existing_type=sa.String(length=60),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
