"""add audit relations asset

Revision ID: 4b4ff2e9b42b
Revises: 0255751c95d5
Create Date: 2025-09-03 09:58:03.388550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4ff2e9b42b'
down_revision: Union[str, Sequence[str], None] = '0255751c95d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('checked_by', sa.String(length=60), nullable=True))
    op.add_column('assets', sa.Column('authorized_by', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'assets', 'users', ['authorized_by'], ['id'])
    op.create_foreign_key(None, 'assets', 'users', ['checked_by'], ['id'])
    op.alter_column('users', 'location_code',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'location_code',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'authorized_by')
    op.drop_column('assets', 'checked_by')
    # ### end Alembic commands ###
