"""add dep head and assistand to departments table

Revision ID: 771ffdc88eb6
Revises: 70533b633f8d
Create Date: 2025-09-22 15:17:26.597891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771ffdc88eb6'
down_revision: Union[str, Sequence[str], None] = '70533b633f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('department_head_id', sa.String(length=60), nullable=True))
    op.add_column('departments', sa.Column('deputy_head_id', sa.String(length=60), nullable=True))
    op.add_column('departments', sa.Column('county_code', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'departments', 'users', ['department_head_id'], ['id'])
    op.create_foreign_key(None, 'departments', 'users', ['deputy_head_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'county_code')
    op.drop_column('departments', 'deputy_head_id')
    op.drop_column('departments', 'department_head_id')
    # ### end Alembic commands ###
