"""jange locations from string to json

Revision ID: 8b0aa51b8226
Revises: 4b4ff2e9b42b
Create Date: 2025-09-03 12:25:07.334743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0aa51b8226'
down_revision: Union[str, Sequence[str], None] = '4b4ff2e9b42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'location',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="NULL")
    op.add_column('users', sa.Column('location', sa.JSON(), nullable=True))
    op.drop_column('users', 'location_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_code', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('users', 'location')
    op.alter_column('assets', 'location',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
