"""add fields to maintinance and some enums

Revision ID: a0ce087e3924
Revises: 771ffdc88eb6
Create Date: 2025-10-01 21:49:01.606321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ce087e3924'
down_revision: Union[str, Sequence[str], None] = '771ffdc88eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_requests', sa.Column('maintenance_type', sa.Enum('CORRECTIVE', 'PREVENTIVE', 'MAJOR', 'MANUFACTURER', 'REFURBISHMENT', 'ENHANCEMENT', 'DEFERRED', name='maintenancetype'), nullable=False))
    op.add_column('maintenance_requests', sa.Column('issue_category', sa.Enum('MECHANICAL_FAILURE', 'MECHANICAL_ISSUE', 'ELECTRICAL', 'SOFTWARE', 'PHYSICAL_DAMAGE', 'THEFT_LOSS', 'OBSOLESCENCE', 'FIRE_NATURAL', 'COMPLIANCE', 'OTHER', name='issuecategory'), nullable=False))
    op.add_column('maintenance_requests', sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='prioritylevel'), nullable=False))
    op.add_column('maintenance_requests', sa.Column('severity', sa.Enum('MINOR', 'MAJOR', 'CRITICAL', name='severitylevel'), nullable=True))
    op.create_index(op.f('ix_maintenance_requests_issue_category'), 'maintenance_requests', ['issue_category'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_maintenance_type'), 'maintenance_requests', ['maintenance_type'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_priority'), 'maintenance_requests', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_requests_priority'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_maintenance_type'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_issue_category'), table_name='maintenance_requests')
    op.drop_column('maintenance_requests', 'severity')
    op.drop_column('maintenance_requests', 'priority')
    op.drop_column('maintenance_requests', 'issue_category')
    op.drop_column('maintenance_requests', 'maintenance_type')
    # ### end Alembic commands ###
